version: '2'
services:
  db:
    restart: always
    volumes:
      - /data/postgresql:/var/lib/postgresql
      - /data/postgresql/data:/var/lib/postgresql/data
    image: postgres:latest
    environment:
      POSTGRES_DB: instagram_development
      POSTGRES_PASSWORD: root
    container_name: postgre
  rails:
    tty: true
    stdin_open: true
    command: sh -c "rm -r tmp; bundle install; bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    image: rails-api
    depends_on:
      - db
    ports:
      - 0.0.0.0:3000:3000
    environment:
      DB_HOST: postgre
    container_name: web_api_instagram
