default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: root
  password: root
  pool: 5

development:
  <<: *default
  database: instagram_development


test:
  <<: *default
  database: instagram_test
